services:
  db:
    image: mysql:8.0
    container_name: expense-db
    restart: always
    environment:
      MYSQL_DATABASE: ExpenseTracker_db
      MYSQL_ROOT_PASSWORD: Reddy@2003PP
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend  # Points to the backend folder
    image : vishnupratapani/expense-tracker-backend
    container_name: expense-backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/ExpenseTracker_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Reddy@2003PP

  frontend:
    build: ./frontend # Points to the frontend folder
    image : vishnupratapani/expense-tracker-frontend
    container_name: expense-frontend
    ports:
      - "8081:8081"
    stdin_open: true
    tty: true
    depends_on:
      - backend